### ISSUE TITLE
Find the value of X, Y, Z?

### ISSUE THREAD

**Issue by vikaskumar5494** [vinaykumar2491/Project-Loop#12]
![github issues_1](https://cloud.githubusercontent.com/assets/12263067/12506203/35c46710-c113-11e5-9b2a-89a5db75ed41.jpg)

**Comment by vikaskumar5494** [comment]
Solved but getting wrong value for Z.

**Comment by vinaykumar2491** [comment]
can u post snippet of your solution.

**Comment by vikaskumar5494** [comment]
![github issues_2](https://cloud.githubusercontent.com/assets/12263067/12506513/84738574-c115-11e5-8dda-25f344ed1565.jpg)
![github issues_3](https://cloud.githubusercontent.com/assets/12263067/12506514/8520f862-c115-11e5-9c59-5216c2087eba.jpg)

**Comment by vikaskumar5494** [comment]
Disclaimer: Snippets may confuse you!

**Comment by vikaskumar5494** [comment]
Solved!
![github issues_4](https://cloud.githubusercontent.com/assets/12263067/12538317/d2130c3a-c2fc-11e5-8142-0a3527e3c5a6.jpg)
