### ISSUE TITLE
Q: This is a question?

### ISSUE THREAD

**Issue by vinaykumar2491** [vinaykumar2491/Project-Loop#9]
I will write the answer details here and attach the image below.
![capture1](https://cloud.githubusercontent.com/assets/12234745/12377097/be2a4970-bd36-11e5-8a48-1c6f24a8061e.PNG)

**Comment by vinaykumar2491** [comment]
``$ y=\sum_{i=1}^n g(x_i) $``

**Comment by vinaykumar2491** [comment]
```tex
\sum_{x=0}^n f(x)
```

**Comment by vinaykumar2491** [comment]
y^(a+b)^

**Comment by vinaykumar2491** [comment]
http://www.intmath.com/blog/mathematics/katex-a-new-way-to-display-math-on-the-web-9445

**Comment by vinaykumar2491** [comment]
![equation](http://www.sciweavers.org/tex2img.php?eq=1%2Bsin%28mc%5E2%29&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=)

**Comment by vinaykumar2491** [comment]
![equation](http://www.sciweavers.org/tex2img.php?eq=%20%5Calpha%20%20%5Cmp%20%20%5Cvarepsilon%20%20%2B%20%20%5Cdelta%20%20%5Cequiv%20%200&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

**Comment by vinaykumar2491** [comment]
http://www.sciweavers.org/free-online-latex-equation-editor

**Comment by vinaykumar2491** [comment]
![equation]()

**Comment by vikaskumar5494** [comment]
![equation](http://www.sciweavers.org/tex2img.php?eq=%5Cfrac%7Bd%7D%7Bd%5Ctheta%7D%20%5Csin%28%5Ctheta%29%20%3D%20%5Ccos%28%5Ctheta%29&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

**Comment by vinaykumar2491** [comment]
http://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog
